// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/peter-pashchenko/grpcExchangeService/internal/application/dto"

	mock "github.com/stretchr/testify/mock"
)

// Api is an autogenerated mock type for the Api type
type Api struct {
	mock.Mock
}

type Api_Expecter struct {
	mock *mock.Mock
}

func (_m *Api) EXPECT() *Api_Expecter {
	return &Api_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx
func (_m *Api) Call(ctx context.Context) (*dto.ExchangeRatesDTO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *dto.ExchangeRatesDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*dto.ExchangeRatesDTO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *dto.ExchangeRatesDTO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExchangeRatesDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Api_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type Api_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Api_Expecter) Call(ctx interface{}) *Api_Call_Call {
	return &Api_Call_Call{Call: _e.mock.On("Call", ctx)}
}

func (_c *Api_Call_Call) Run(run func(ctx context.Context)) *Api_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Api_Call_Call) Return(_a0 *dto.ExchangeRatesDTO, _a1 error) *Api_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Api_Call_Call) RunAndReturn(run func(context.Context) (*dto.ExchangeRatesDTO, error)) *Api_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewApi creates a new instance of Api. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *Api {
	mock := &Api{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
